#!/usr/bin/env python3
"""Emit `eccn:<code>` -> `ccl:<code>` equivalences for every ECCN in the pack.

Why this exists
---------------
OpenContracts' Tier-2a shape grammar (OpenContracts PR #2276) recognises
"ECCN 3A611" from the literal "ECCN" anchor alone and emits the SHAPE-level
key `eccn:3a611` — deliberately not `ccl:`, because `ccl` is the prefix this
pack happens to give its Commerce Control List corpus, and core emitting it
would hardcode one pack's naming into the framework.

Folding the shape keys onto this pack's keys therefore happens here, exactly
as the pack already folds the LLM-extracted `act:eccn-*` surface forms. A
prefix-level rewrite rule (`eccn:N -> ccl:N`) would be the tidier mechanism,
but a pack's `rewrite_rules` are not loaded (authority_mapping_loader reads
`equivalences` only), so the mapping is expressed as explicit per-key rows —
one per ECCN in `specs/ccl.json`.

Run from the pack directory and paste the output into the `equivalences` list
in `authority_mappings.ear.yaml` (replace the previous generated block):

    python3 gen_eccn_equivalences.py
"""
import json
import re
from pathlib import Path

SPEC = Path(__file__).parent / "specs" / "ccl.json"

# ECCN structure: digit, letter A-E, three digits, optional dotted paragraph.
# Supplement documents (`ccl:supplement-1-part-774`) are not ECCNs and get no
# row — the extractor can never emit an `eccn:` key for them.
ECCN_KEY = re.compile(r"ccl:(\d[a-e]\d{3}(?:\.[a-z0-9.]+)?)")

codes = sorted(
    m.group(1)
    for s in json.loads(SPEC.read_text())["sections"]
    if (m := ECCN_KEY.fullmatch(s["key"]))
)

print(f"# ECCN shape-key equivalences — GENERATED by gen_eccn_equivalences.py")
print(f"# ({len(codes)} rows, one per ECCN in specs/ccl.json). The Tier-2a ECCN")
print(f"# grammar emits shape-level `eccn:` keys; these rows fold them onto this")
print(f"# pack's `ccl:` keys. Regenerate after any change to specs/ccl.json.")
for code in codes:
    print(f"- from_key: eccn:{code}")
    print(f"  to_key: ccl:{code}")
